UMC-ZIC/ZIC

src/main/java/com/umc7/ZIC/apiPayload/exception/handler/GeneralException.java
=> main#2: 빠진 파일 추가

src/main/java/com/umc7/ZIC/common/domain/BaseEntity.java, src/main/java/com/umc7/ZIC/common/domain/enums/Instrument.java, src/main/java/com/umc7/ZIC/owner/domain/Owner.java, src/main/java/com/umc7/ZIC/user/domain/User.java
> 이용자, 대여자 entity 구현, 공통 entity 추가, 악기 종류 enum 추가
=> feature#3: 이용자, 대여자 entity 구현, 공통 entity 구성 추가, 악기 종류 추가

src/main/java/com/umc7/ZIC/common/domain/Instrument.java, src/main/java/com/umc7/ZIC/common/domain/enums/InstrumentType.java, src/main/java/com/umc7/ZIC/common/domain/enums/Region.java, src/main/java/com/umc7/ZIC/common/domain/enums/RegionType.java, src/main/java/com/umc7/ZIC/user/domain/User.java, src/main/java/com/umc7/ZIC/user/domain/UserInstrument.java
> 지역, 악기 entity 추가 및 유저_악기 매핑 엔티디, 유저와 지역 매핑 추가
=> feature3: 지역, 악기 entity 추가 및 유저_악기 매핑 엔티디, 유저와 지역 매핑 추가

src/main/java/com/umc7/ZIC/common/domain/Instrument.java
> bugfix8 branch
> 엔티티 잘못된 mappedBy 수정
=> bugfix: entity mappedBy 수정

src/main/java/com/umc7/ZIC/common/domain/Region.java, src/main/java/com/umc7/ZIC/common/domain/enums/InstrumentType.java, src/main/java/com/umc7/ZIC/common/domain/enums/RegionType.java, src/main/java/com/umc7/ZIC/user/domain/User.java
#10 
> Region 엔티티 클래스 위치 수정 및 enum 값 대문자로 변경
=> refactor: Region 엔티티 클래스 위치 수정 및 enum 값 대문자로 변경

src/main/java/com/umc7/ZIC/common/domain/enums/InstrumentType.java, src/main/java/com/umc7/ZIC/instrument/domain/Instrument.java, src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoom.java, src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoomDetail.java, src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoomInstrument.java, src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoomLike.java
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
practiceRoom, practiceRoomDetail, practiceRoomLike, Instrument 등 엔티티 추가
=> Feature:  practiceRoom 도메인 관련 엔티티 추가

src/main/java/com/umc7/ZIC/apiPayload/exception/ApiResponse.java, src/main/java/com/umc7/ZIC/apiPayload/exception/handler/ExceptionAdvice.java
#17 
> record 변경에 따른 getter 메서드를 record 형식으로 변경
=> bugfix: record 변경에 따른 getter 메서드를 record 형식으로 변경

src/main/java/com/umc7/ZIC/common/domain/Region.java, src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoomDetail.java, src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomDetailRepository.java, src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomLikeRepository.java, src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomRepository.java, src/main/java/com/umc7/ZIC/practiceRoom/repository/temp/OwnerRepository.java, src/main/java/com/umc7/ZIC/practiceRoom/repository/temp/RegionRepository.java, src/main/java/com/umc7/ZIC/practiceRoom/repository/temp/UserRepository.java, src/main/java/com/umc7/ZIC/user/domain/User.java, src/test/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomDetailRepositoryTest.java, src/test/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomLikeRepositoryTest.java, src/test/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomRepositoryTest.java
#16
> ex) #이슈번호, #이슈번호
연습실, 연습실내부방, 좋아요 레포지터리 및 레포지터리 테스트 구현
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
=> feature: 연습실 관련 레포지터리 구현

src/main/java/com/umc7/ZIC/user/domain/enums/RoleType.java
=> refactor: enum userType 추가

src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoom.java, src/main/java/com/umc7/ZIC/user/domain/UserInstrument.java
owner entity -> user entity 변경
=> feature: user-owner 통합에 따른 entity 수정

src/main/java/com/umc7/ZIC/user/repository/UserRepositoryCustom.java
=> feature: repository 커스텀 인터페이스 추가

src/main/resources/application.yml
=> bugfix: 카카오 scope 설정 이메일 동의 해결

src/main/java/com/umc7/ZIC/security/SecurityConfig.java
=> bugfix: csrf 비활성화

src/main/java/com/umc7/ZIC/common/controller/ReservationPageController.java, src/main/java/com/umc7/ZIC/reservation/controller/ReservationRestController.java, src/main/java/com/umc7/ZIC/reservation/converter/KakaoPayConverter.java, src/main/java/com/umc7/ZIC/reservation/converter/ReservationConverter.java, src/main/java/com/umc7/ZIC/reservation/domain/Reservation.java, src/main/java/com/umc7/ZIC/reservation/domain/ReservationDetail.java, src/main/java/com/umc7/ZIC/reservation/dto/PaymentRequestDTO.java, src/main/java/com/umc7/ZIC/reservation/dto/PaymentResponseDTO.java, src/main/java/com/umc7/ZIC/reservation/dto/ReservationRequestDTO.java, src/main/java/com/umc7/ZIC/reservation/dto/ReservationResponseDTO.java, src/main/java/com/umc7/ZIC/reservation/repository/ReservationDetailRepository.java, src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepository.java, src/main/java/com/umc7/ZIC/reservation/service/KakaoPayService.java, src/main/java/com/umc7/ZIC/reservation/service/KakaoPayServiceImpl.java, src/main/java/com/umc7/ZIC/reservation/service/ReservationCommandService.java, src/main/java/com/umc7/ZIC/reservation/service/ReservationCommandServiceImpl.java, src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryService.java, src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryServiceImpl.java, src/main/resources/application.yml, src/main/resources/templates/KakaoReady.html
> #15 feature : 연습실 결제 API 구현
- 연습실 예약을 결제하기 위한 카카오 페이 결제 API 구현
- 연슬실 예약 내역을 조회하기 위한 API 구현
=> feature: 연습실 결제 및 예약 내역 조회 API 구현

src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoom.java, src/main/java/com/umc7/ZIC/reservation/controller/ReservationRestController.java, src/main/java/com/umc7/ZIC/reservation/service/KakaoPayServiceImpl.java, src/main/java/com/umc7/ZIC/user/controller/UserController.java, src/main/java/com/umc7/ZIC/user/converter/UserConverter.java, src/main/java/com/umc7/ZIC/user/dto/UserResponseDto.java, src/main/java/com/umc7/ZIC/user/repository/UserRepositoryCustom.java, src/main/java/com/umc7/ZIC/user/repository/UserRepositoryImpl.java, src/main/java/com/umc7/ZIC/user/service/UserService.java, src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
> #33 feture: 연습실 주인 수익 데이터 조회 API 구현
> - 연습실 대여자 수익 데이터 조회 API 구현
> - PracticeRoom 엔티티에 양방향 연결 추가
=> feature: 연습실 대여자 수익 데이터 조회 API 구현

src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc7/ZIC/apiPayload/exception/handler/InstrumentHandler.java, src/main/java/com/umc7/ZIC/common/repository/InstrumentRepository.java, src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java, src/main/java/com/umc7/ZIC/security/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/umc7/ZIC/security/SecurityConfig.java, src/main/java/com/umc7/ZIC/user/controller/UserController.java, src/main/java/com/umc7/ZIC/user/converter/UserConverter.java, src/main/java/com/umc7/ZIC/user/domain/User.java, src/main/java/com/umc7/ZIC/user/dto/UserRequestDto.java, src/main/java/com/umc7/ZIC/user/dto/UserResponseDto.java, src/main/java/com/umc7/ZIC/user/service/UserService.java, src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java, src/main/resources/templates/login.html
#14 
> 카카오 가입 response 수정 및 추가정보 구현
=> feature: 카카오 가입 response 수정 및 추가정보 구현

src/main/java/com/umc7/ZIC/user/controller/UserController.java, src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
=> feature: 엑세스 토큰 생성 테스트 api 생성

src/main/java/com/umc7/ZIC/user/controller/OwnerController.java, src/main/java/com/umc7/ZIC/user/controller/UserController.java
> #14 
> user, owner controller 분리
=> refactor: user, owner controller 분리

src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc7/ZIC/security/CustomOAuth2UserService.java, src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java, src/main/resources/application.yml
=> Feature: 예외 처리 추가

src/main/java/com/umc7/ZIC/common/domain/enums/RegionType.java, src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
=> feature: 지역 처리 구현

src/main/java/com/umc7/ZIC/reservation/controller/ReservationRestController.java, src/main/java/com/umc7/ZIC/reservation/converter/KakaoPayConverter.java, src/main/java/com/umc7/ZIC/reservation/converter/ReservationConverter.java, src/main/java/com/umc7/ZIC/reservation/domain/Reservation.java, src/main/java/com/umc7/ZIC/reservation/domain/enums/Status.java, src/main/java/com/umc7/ZIC/reservation/dto/PaymentRequestDTO.java, src/main/java/com/umc7/ZIC/reservation/dto/ReservationRequestDTO.java, src/main/java/com/umc7/ZIC/reservation/dto/ReservationResponseDTO.java, src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepository.java, src/main/java/com/umc7/ZIC/reservation/service/KakaoPayService.java, src/main/java/com/umc7/ZIC/reservation/service/KakaoPayServiceImpl.java, src/main/java/com/umc7/ZIC/reservation/service/ReservationCommandService.java, src/main/java/com/umc7/ZIC/reservation/service/ReservationCommandServiceImpl.java, src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryServiceImpl.java, src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java, src/main/java/com/umc7/ZIC/user/controller/OwnerController.java, src/main/java/com/umc7/ZIC/user/controller/UserController.java, src/main/resources/templates/KakaoReady.html
> #43 feature : 
예약 API에 JWT 토큰 적용
> - 연습실 대여자 수익 확인 API를 OwnerController로 이동
> - 예약 API에 jwt 적용
> - 예약 엔티티에 결제 상태인 status 추가
=> feature#43-reservation-api-with-JWT

src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc7/ZIC/security/CustomUserDetail.java, src/main/java/com/umc7/ZIC/security/JwtFilter.java, src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java, src/main/java/com/umc7/ZIC/security/SecurityConfig.java, src/main/java/com/umc7/ZIC/security/handler/CustomAccessDeniedHandler.java, src/main/java/com/umc7/ZIC/security/handler/CustomAuthenticationEntryPoint.java, src/main/java/com/umc7/ZIC/security/handler/ExceptionFilter.java, src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
> #41 
> security filter 설정 및 권한, jwt토큰 에러 핸들러 작성
=> feature: security filter 설정 및 권한, jwt토큰 에러 핸들러 작성

src/main/java/com/umc7/ZIC/security/SecurityConfig.java
=> reafactor: SecurityConfig 불필요한 코드 제거

src/main/java/com/umc7/ZIC/common/controller/TestLoginController.java, src/main/java/com/umc7/ZIC/user/controller/OwnerController.java, src/main/java/com/umc7/ZIC/user/controller/UserController.java
=> bugfix: security 권한 필요로 인한 테스트 코드 api 위치 변경

src/main/java/com/umc7/ZIC/common/controller/TestLoginController.java
=> bugfix: endpoint 충돌 수정

.gitignore, src/main/java/com/umc7/ZIC/common/controller/ReservationPageController.java, src/main/java/com/umc7/ZIC/reservation/controller/ReservationRestController.java, src/main/java/com/umc7/ZIC/reservation/converter/KakaoPayConverter.java, src/main/java/com/umc7/ZIC/reservation/dto/PaymentRequestDTO.java, src/main/java/com/umc7/ZIC/reservation/dto/PaymentResponseDTO.java, src/main/java/com/umc7/ZIC/reservation/dto/ReservationResponseDTO.java, src/main/java/com/umc7/ZIC/reservation/service/KakaoPayService.java, src/main/java/com/umc7/ZIC/reservation/service/KakaoPayServiceImpl.java, src/main/java/com/umc7/ZIC/security/SecurityConfig.java, src/main/java/com/umc7/ZIC/user/controller/OwnerController.java, src/main/java/com/umc7/ZIC/user/repository/UserRepositoryImpl.java, src/main/resources/application.yml
> - .env 파일 적용 및 .gitignore 변경 
> - KaKao Pay 결제 취소 API 구현 
> - 예약 관련 API에 jwt 권한 체크 부여
=> feature#45 .env파일 적용 및 결제 취소 API 구현

src/main/java/com/umc7/ZIC/config/SwaggerConfig.java, src/main/java/com/umc7/ZIC/security/JwtFilter.java
=> bugfix: security filter

.github/workflows/deploy.yml
> #58 chore: AWS 배포 및 GitHub Action 활성화
> GitHub Action 활성화
=> chore#58-AWS-CI-CD

src/main/java/com/umc7/ZIC/config/WebMvcConfig.java
=> feature: CROS 설정

.github/workflows/deploy.yml, src/main/java/com/umc7/ZIC/reservation/service/KakaoPayServiceImpl.java, src/main/java/com/umc7/ZIC/security/JwtFilter.java, src/main/resources/application.yml
> #63 test: AWS 배포 테스트
> deploy.yml 변경
=> chore: deploy.yml 변경

src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomRequestDto.java, src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
=> remove: 위도 경도 notnull 제거

src/main/java/com/umc7/ZIC/user/controller/OwnerController.java, src/main/java/com/umc7/ZIC/user/controller/UserController.java
>#14
> swagger 이용자 대여자 추가 정보 기입 설명 추가
=> feature: swagger api 설명 추가

src/main/java/com/umc7/ZIC/common/controller/TestLoginController.java
> #79 #14 
> 테스트 api refresh로 되어 있는 부분 access로 수정
=> fix: refresh 토큰 -> access 토큰 수정

src/main/java/com/umc7/ZIC/common/controller/TestLoginController.java, src/main/java/com/umc7/ZIC/security/CustomOAuth2UserService.java, src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java, src/main/java/com/umc7/ZIC/security/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
=> feature: jwt토큰 유저 이름 추가

src/main/java/com/umc7/ZIC/security/CustomOAuth2UserService.java, src/main/java/com/umc7/ZIC/security/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/umc7/ZIC/user/domain/User.java, src/main/resources/application.yml
=> feature: 카카오 프로필 사진 저장

src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java, src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java, src/main/resources/application.yml
> #89 
> to develop merge 이후 오류 난 부분 수정
=> bugfix: merge 이후 수정 안 된 부분 수정

src/main/java/com/umc7/ZIC/common/domain/Region.java, src/main/java/com/umc7/ZIC/user/domain/User.java
> #94 
> User 엔티티 OneToOne 을 ManyToOne으로 설정
=> bugfix: OneToOne 을 ManyToOne으로 설정

src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
> #96 
> 대여자 가입시 practiceRoom_instrument DB 저장
=> bugfix: practiceRoom_instrument DB 저장

src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
=> bugfix: 연습실 이름을 비즈니스 이름으로 수정

src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepositoryCustom.java, src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepositoryImpl.java, src/main/java/com/umc7/ZIC/user/controller/KakaoLoginPageController.java, src/main/java/com/umc7/ZIC/user/controller/OwnerController.java, src/main/java/com/umc7/ZIC/user/controller/UserController.java, src/main/java/com/umc7/ZIC/user/converter/UserConverter.java, src/main/java/com/umc7/ZIC/user/dto/UserResponseDto.java, src/main/java/com/umc7/ZIC/user/repository/UserRepositoryCustom.java, src/main/java/com/umc7/ZIC/user/repository/UserRepositoryImpl.java, src/main/java/com/umc7/ZIC/user/service/UserService.java, src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
> #93 
> 이용자 마이페이지 api 구현 및 일부 메서드 대문자로 수정
=> feature: 이용자 마이페이지 구현, reafactor: 일부 메서드 대문자로 수정

src/main/java/com/umc7/ZIC/user/controller/OwnerController.java, src/main/java/com/umc7/ZIC/user/controller/UserController.java, src/main/java/com/umc7/ZIC/user/converter/UserConverter.java, src/main/java/com/umc7/ZIC/user/dto/UserResponseDto.java, src/main/java/com/umc7/ZIC/user/service/UserService.java, src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
> #96 
> 대여자 가입시 연습실 id도 response. 되게 변경. 메서드 이름 대문자로 시작하게 변경
=> Bugfix: 대여자 가입시 연습실 id도 response. refactor: 메서드 이름 변경

build.gradle, src/main/java/com/umc7/ZIC/common/util/RedisUtil.java, src/main/java/com/umc7/ZIC/config/RedisConfig.java, src/main/resources/application.yml
=> feature: redis 구현

src/main/java/com/umc7/ZIC/security/SecurityConfig.java
> #64 
> cors 시큐리티에 적용 및 preflight 처리
=> feature: cors 시큐리티에 적용설정 및 preflight 요청 처리

src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java
> #108 
> 시연 대비를 위한 jwt토큰 시간 변경
=> feature: jwt토큰 시간 변경

src/main/java/com/umc7/ZIC/security/OAuth/CustomOAuth2User.java, src/main/java/com/umc7/ZIC/security/OAuth/CustomOAuth2UserService.java, src/main/java/com/umc7/ZIC/security/OAuth/OAuith2AuthenticationFailureHandler.java, src/main/java/com/umc7/ZIC/security/OAuth/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/umc7/ZIC/security/SecurityConfig.java
> #109 
> OAuth 클래스 폴더 만들어서 정리
=> rename: OAuth 관련 클래스 위치 변경

src/main/java/com/umc7/ZIC/security/SecurityConfig.java
=> feature: cors 허용 도메인 정리

src/main/java/com/umc7/ZIC/security/OAuth/OAuth2AuthenticationSuccessHandler.java
=> feature: 개발 테스트 로그인 성공 url 변경

src/main/java/com/umc7/ZIC/security/OAuth/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/umc7/ZIC/security/SecurityConfig.java
=> CICD: Main 브랜치로 병합

src/main/java/com/umc7/ZIC/user/controller/UserController.java
=> feature: 마이페이지 스웨거 설명 추가

src/main/java/com/umc7/ZIC/common/controller/TestLoginController.java
> ex) #이슈번호, #이슈번호
> test API에 스웨거 설명 추가
=> feature: 테스트용 API 스웨거 설명 추가
